/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepFilter struct {
	// The replication policy filter kind. The valid values are project, repository and tag.
	Kind string `json:"kind,omitempty"`
	// The replication policy filter pattern.
	Pattern string `json:"pattern,omitempty"`
	// This map object is the replication policy filter metadata.
	Metadata interface{} `json:"metadata,omitempty"`
}
