/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectReq struct {
	// The name of the project.
	ProjectName string `json:"project_name,omitempty"`
	// The public status of the project.
	Public int32 `json:"public,omitempty"`
	// Whether content trust is enabled or not. If it is enabled, user cann't pull unsigned images from this project.
	EnableContentTrust bool `json:"enable_content_trust,omitempty"`
	// Whether prevent the vulnerable images from running.
	PreventVulnerableImagesFromRunning bool `json:"prevent_vulnerable_images_from_running,omitempty"`
	// If the vulnerability is high than severity defined here, the images cann't be pulled.
	PreventVulnerableImagesFromRunningSeverity string `json:"prevent_vulnerable_images_from_running_severity,omitempty"`
	// Whether scan images automatically when pushing.
	AutomaticallyScanImagesOnPush bool `json:"automatically_scan_images_on_push,omitempty"`
}
