/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepPolicy struct {
	// The policy ID.
	Id int64 `json:"id,omitempty"`
	// The policy name.
	Name string `json:"name,omitempty"`
	// The description of the policy.
	Description string `json:"description,omitempty"`
	// The project list that the policy applys to.
	Projects []Project `json:"projects,omitempty"`
	// The target list.
	Targets []RepTarget `json:"targets,omitempty"`
	Trigger *RepTrigger `json:"trigger,omitempty"`
	// The replication policy filter array.
	Filters []RepFilter `json:"filters,omitempty"`
	// Whether to replicate the existing images now.
	ReplicateExistingImageNow bool `json:"replicate_existing_image_now,omitempty"`
	// Whether to replicate the deletion operation.
	ReplicateDeletion bool `json:"replicate_deletion,omitempty"`
	// The create time of the policy.
	CreationTime string `json:"creation_time,omitempty"`
	// The update time of the policy.
	UpdateTime string `json:"update_time,omitempty"`
	// The error job count number for the policy.
	ErrorJobCount int32 `json:"error_job_count,omitempty"`
}
